
class App {
    +App();
	+~App();
	+void run();
    #std::unique_ptr<Game> _game;
}

class Entity{
	+ Entity(int entityId, int uniqueId, int posX, int posY);;
	+ ~Entity();
    +int getEntityId() const;
	+void updatePosition(int &x, int &y);
	+sf::Vector2f getPosition() const;
    #sf::Vector2f _pos;
	#int _entityId;
	#int _uniqueId;

}

class Game{
	+void initNetwork();
    +void startLoop();
    +void unpack();
    +void renderEntities();
    +void createEntity(int &uniqueId, int &posX, int &posY);
    +void updateEntity(int &id, int &posX, int &posY);
    +void deleteEntity(int &id);
    +void initSprites();
    +std::shared_ptr<GameEngine> getGameEngine() const;
	+void renderBackground();

    #std::shared_ptr<GameEngine> _gameEngine;
    #std::shared_ptr<sf::RenderWindow> _window;
    #std::unique_ptr<Network> _network;
    #std::unique_ptr<Menu> _menu;
    #std::vector<std::unique_ptr<Entity>> _entities;
    #std::unordered_map<int, std::pair<sf::Texture, sf::Sprite>> _sprites;
    #std::shared_ptr<bool> _isMenu = std::make_shared<bool>(true);
    #sf::Event event;

}
enum EEntities{
    PLAYER1
    PLAYER2
    PLAYER3
    PLAYER4
    MISSILE
    MOB1
    MOB2
    MOB3
    MOB4
    ENTITIES_NUMBER
}

class GameEngineClient{
    +GameEngine();
	+~GameEngine();
	+void TreatmentEvent(sf::Event event);
	+void songLevel(bool level);
	+void playSong();
	+void songPause();

    #bool _isSong = false;
	#int _volumeSong = 50;
	#bool _songStatus = true;
	#sf::Music _music;
}

class Menu{
    +Menu(std::shared_ptr<sf::RenderWindow> window, std::shared_ptr<bool> isMenu);
    +~Menu();
    +void initAssets();
    +void renderMenu();
    +void eventMenu();
    +void displayMenuString();
    +void eventPressed();
    +void eventInput();
    +void renderEntitiesMenu();
	+std::string getIp();
    +std::string getPort();
    +void detachIpPort();
    #sf::Texture _text_background;
    #sf::Sprite _background;
    #sf::Texture _text_logo;
    #sf::Sprite _logo;
    #std::shared_ptr<sf::RenderWindow> _window;
    #sf::Event _event;
    #std::shared_ptr<bool> _isMenu;
    #bool _isPlay = false;
    #std::string _ip = "";
	#std::string _port = "";
    #std::vector<std::string> gameName;
    #sf::String _playerInput;
    #sf::Font _font;
    #std::vector<std::string> _strMenu{"Start", "Exit"};
    #int position = 0;
}

class Network {
    +Network();
    +~Network();

    +void bindSocket();
    +void sendData(const char data[]);
    +char *receiveData();
    #sf::UdpSocket _socket;
	+sf::Packet _packet;
}

namespace EntityNamespace{
enum e_type{
    PLAYER1,
    PLAYER2,
    PLAYER3,
    PLAYER4,
    MISSILE_ALLY,
    MISSILE_MOB,
    MOB1,
    MOB2,
    MOB3,
    MOB4,
    ENUM_SIZE
}

class IEntity{
	+IEntity() = default;
	+virtual ~IEntity() = default;
	+virtual const std::atomic<int> &getId() const noexcept = 0;
	+virtual const std::atomic<int> &getPosX() const noexcept = 0;
	+virtual void setPosX(const int x) noexcept = 0;
	+virtual const std::atomic<int> &getPosY() const noexcept = 0;
	+virtual void setPosY(const int y) noexcept = 0;
	+virtual const std::atomic<int> &getType() const noexcept = 0;
	+virtual void setType(type type) noexcept = 0;
	+virtual void move(const int x, const int y) noexcept = 0;
	+virtual bool limits(const int x, const int y) const noexcept = 0;
}



class GameEntity{
+GameEntity();
+~GameEntity() = default;

+const std::atomic<int> &getId() const noexcept final;
+const std::atomic<int> &getPosX() const noexcept final;
+void setPosX(const int x) noexcept final;
+const std::atomic<int> &getPosY() const noexcept final;
+void setPosY(const int y) noexcept final;
+const std::atomic<int> &getType() const noexcept final;
+void setType(type type) noexcept final;
+void move(const int x, const int y) noexcept final;
+bool limits(const int x, const int y) const noexcept final;
+bool getRemoveEntity() const noexcept;
+void setRemoveEntity() noexcept;
+void ia() noexcept;

-std::atomic<int> _posX;
-std::atomic<int> _posY;
-std::atomic<int> _entityId;
-std::atomic<int> _type;
-std::atomic<bool> _removeEntity;
-int _loopCount = 0;
-bool _isShooting = false;
}
IEntity --|> GameEntity
class Missile{
	+Missile() = default;
	+Missile(const bool ally);
	+~Missile() = default;
	+void setAlly(const bool ally) noexcept;
	+const std::atomic<bool> &getAlly() const noexcept;
	-std::atomic<bool> _ally;

}
GameEntity --|> Missile

class Mob {
    +Mob();
    +~Mob() = default;
    +void path(int path);
	+void shootingTime();
	-int _healthPoints;
	-int _movements = 0;
	-int _lastShoot = 0;
}
GameEntity --|> Mob

class Player{
	+Player();
	+Player(const std::string &ip, const unsigned short port);
	+~Player() = default;

	+void setIpAddress(const std::string &address) noexcept;
	+const std::string &getIpAddress() const noexcept;
	+void setPort(const unsigned short port) noexcept;
	+const std::atomic<unsigned short> &getPort() const noexcept;
	+void setConnected(const bool connected) noexcept;
	+const std::atomic<bool> &isConnected() const noexcept;
	+void setId(const int id) noexcept;
	+void setLives(const int lives) noexcept;
	+const std::atomic<int> &getLives() const noexcept;
	+void ia();

	-std::string _ip = "127.0.0.1";
	-std::atomic<unsigned short> _port;
	-std::atomic<bool> _connected;
	-std::atomic<int> _lives;
}

GameEntity --|> Player
}

class GameServer{
	+GameServer();
	+~GameServer() = default;
	+void gameLoop();
	+void addPlayer(sf::Packet &packet) noexcept;
	+void removeDestroyedEntities(size_t);
	+void mobGeneration() noexcept;
	+std::unique_ptr<GameEngine> _gameEngine = nullptr;
	+std::vector<std::unique_ptr<Player>> _players = {};
	+std::vector<std::unique_ptr<GameEntity>> _entities = {};
}

class GameEngine{
    +GameEngine();
    +~GameEngine() = default;

    +void checkCollisions(std::vector<std::unique_ptr<GameEntity>> &) noexcept;
	+bool checkPosition(GameEntity &, GameEntity &) const noexcept;
	+bool checkEntityType(GameEntity &, GameEntity &) const noexcept;
	+void mobIA(GameEntity &) noexcept;
	+bool isGameInProgress() const noexcept;
	+void setGameStart(bool) noexcept;
	-bool _gameIP = false;
}

namespace NetworkMethods{
    enum e_type{
        PACKET_PLAYER_NEW
		PACKET_PLAYER
		PACKET_ENTITY
		PACKET_END
        }
}

class NetworkUDP{
	+NetworkUDP() = default;
	+NetworkUDP(unsigned short port);
	+virtual ~NetworkUDP();

	+void setPort(unsigned short port) noexcept;
	+unsigned short getPort() const noexcept;
	+void bind();
	+void block(const bool state);
	+void listen(sf::Packet &packet, sf::IpAddress &remoteAddress,unsigned short &remotePort) noexcept;
	+bool send(sf::Packet &packet, sf::IpAddress &remoteAddress,unsigned short &remotePort);

	-sf::UdpSocket _socket;
	-unsigned short _port = 0;
	-sf::Socket::Status _status = sf::Socket::Status::NotReady;
}

NetworkMethods --|> NetworkUDP

class std::exception {

}

class Exception{
	+Exception() = default;
	+Exception(const std::string &msg);
	+~Exception() = default;

	+const char *what() const noexcept;

	-std::string _msg = "An internal error occured.";
}

std::exception --|> Exception


namespace AppNameSpace {
	class CLI{
		+CLI() = default;
		+CLI(int argc, char **argv);
		+~CLI() = default;
		+void launchCLI();
		+static vecStr explode(const std::string &str, const char delim);
		-bool callCommand(const std::string &str);
		+std::unique_ptr<Instance> _instance = nullptr;
		-int _argc = 0;
		-std::vector<std::string> _args;
		-std::vector<std::string> _argv;
		-const std::map<std::string, int> _cmdList = {
			{"start", CLI::CMD_START},
			{"state", CLI::CMD_STATE},
			{"help", CLI::CMD_HELP},
			{"exit", CLI::CMD_EXIT}
		};
	}
    class Commands
	{
		enum Enum{
			CMD_START,
			CMD_STATE,
			CMD_HELP,
			CMD_EXIT
		};
		+Commands() = default;
		+virtual ~Commands() = default;
		+bool dispatcher(const int type, const std::vector<std::string> &args);
		-bool start(const std::vector<std::string> &args);
		-bool state() noexcept;
		-bool help() const noexcept;
		-bool exit() const noexcept;
	}
    Commands --|> CLI
}

class Fork{
	Enum{
		FORK_PARENT
		FORK_CHILD
	};

	+Fork() = default;
	+virtual ~Fork() = default;

	+void fork();
	+void kill() const;
	+constexpr void killDebug(const bool state, const pid_t pid) const noexcept;
	+bool isParent() const noexcept;
	+std::vector<pid_t> &getProcess() noexcept;
	+pid_t getLastPid() const noexcept;

	-pid_t _last = 0;
	-int _fork = FORK_PARENT;
	-std::vector<pid_t> _process_id;
}

class Instance{
	+Instance() = default;
	+Instance(unsigned short port);
	+~Instance();

	+void setPort(unsigned short port) noexcept;
	+unsigned short getPort() const noexcept;
	+void run();
	+unsigned int countInstances() const noexcept;
	+void instance();

	-unsigned short _port = 0;
	-std::vector<std::thread> _instances;
}


class Server{
	+Server() = default;
	+Server(unsigned short port);
	+~Server() = default;
	+void network();
	+void networkDebug(const sf::IpAddress &addr, const unsigned short port);
	-void extract(sf::Packet &packet);
	+std::vector< std::thread> _threads;
	+std::atomic<bool> _run;
	+GameServer _game;
}

NetworkUDP --|> Server